name: Build JAR

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.2'

      - name: Extract project
        run: |
          rm -rf project
          unzip -q FakeDoomsdayClient-FINAL.zip -d project

      - name: Build JAR
        working-directory: project
        run: gradle build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: FakeDoomsdayClient-JAR
          path: project/build/libs/*.jar
